Initial commit of FusionDirectory
stuvusIT/fusiondirectory pull request #1
Opened 2017-06-16 20:35 UTC by dasJ

2017-06-17 02:39 UTC, Mr-Pi submitted a review, later dismissed

2017-06-17 02:39 UTC, Mr-Pi commented on tasks/install_deb.yml
> +  changed_when: false
This is done by a common role and should not be done here.

2017-06-17 02:39 UTC, Mr-Pi commented on vars/main.yml
> +plugins_download_url: "https://repos.fusiondirectory.org/sources/{{ fusiondirectory_major_version }}/fusiondirectory/fusiondirectory-plugins-{{ fusiondirectory_version }}.tar.gz"
Please prefix variables

2017-06-17 02:39 UTC, Mr-Pi commented on tasks/plugins.yml
> +  command: rsync -varuEAXH --delete "{{ item }}/" "{{ local_download_dir }}/fd-plugins/{{ item | basename }}/"
please add rsync to packages to be installed.

2017-06-17 10:21 UTC, SlothOfAnarchy commented on tasks/install_deb.yml
> +  changed_when: false
Not everyone will use or execute the common role

2017-06-17 11:09 UTC, SlothOfAnarchy requested changes

2017-06-17 11:09 UTC, SlothOfAnarchy commented on README.md
> +| `fusiondirectory_logging`          | `true`             | Enable logging                                                                                  |
Where are the logs placed? Is it configurable?

2017-06-17 11:09 UTC, SlothOfAnarchy commented on README.md
> +A dpkg- or pacman-based Linux distribution.
There are no pacman tasks yet.

2017-06-17 11:09 UTC, SlothOfAnarchy commented on tasks/plugins.yml
> +  changed_when: false
can this setup command be executed multiple times without changes or sideeffects?

2017-06-18 14:29 UTC, dasJ commented on tasks/install_deb.yml
> +  changed_when: false
@Mr-Pi Are you serious???

2017-06-18 14:30 UTC, dasJ commented on vars/main.yml
> +plugins_download_url: "https://repos.fusiondirectory.org/sources/{{ fusiondirectory_major_version }}/fusiondirectory/fusiondirectory-plugins-{{ fusiondirectory_version }}.tar.gz"
No. They are role-internal and cannot be changed

2017-06-18 14:30 UTC, dasJ commented on README.md
> +A dpkg- or pacman-based Linux distribution.
Damn

2017-06-18 14:30 UTC, dasJ commented on README.md
> +| `fusiondirectory_logging`          | `true`             | Enable logging                                                                                  |
Syslog, so no

2017-06-18 14:30 UTC, dasJ commented on tasks/plugins.yml
> +  changed_when: false
Yes, I tried

2017-06-18 14:40 UTC, dasJ commented on tasks/plugins.yml
> +  command: rsync -varuEAXH --delete "{{ item }}/" "{{ local_download_dir }}/fd-plugins/{{ item | basename }}/"
Done

2017-07-03 20:03 UTC, dasJ commented
@Mr-Pi @SlothOfAnarchy Pls rereview

2017-07-04 10:15 UTC, SlothOfAnarchy approved these changes

2017-07-04 10:16 UTC, SlothOfAnarchy commented
@Mr-Pi Your requested changes have been implemented or discussed. Can you approve and merge this?
Thanks!

2017-07-04 19:43 UTC, merged